### PR TITLE
enable submitting alternate address where there was no possibility before

### PR DESCRIPTION
**Pull request by ddellacosta**
https://www.pivotaltracker.com/story/show/157090660

This is the bare minimum I could do to make this work. The UI still sucks as discussed with Maria and Troy--I'll be submitting a second PR ASAP to hopefully make it slightly more obvious what the user should do.

See https://github.com/votinginfoproject/vip-embeddable-tool/commit/1ced5bc0af4de3c1f807035962f24ac11641db5a#diff-aa1adde62301a7810fc28dbfe926891d for history.

### CODE REVIEW

**Comment by ddellacosta** [comment]
@tank157 Funny, that's exactly what I said to myself when I tweaked this code... 😆

**Comment by ddellacosta** [comment]
@tank157 Would you mind re-reviewing? I decided just to throw my updated changes in this PR because they are pretty minimal and straightforward.

**Comment by ddellacosta** [comment]
微妙な反応だね。Thanks...haha

**Comment by tank157** [comment]
I wonder if subtle reaction has more significance than I understand.

**Pull request merged**
